// proto/shipment.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: proto/shipment.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShipmentService_CalculateRates_FullMethodName       = "/shipment.ShipmentService/CalculateRates"
	ShipmentService_GetAvailableCouriers_FullMethodName = "/shipment.ShipmentService/GetAvailableCouriers"
	ShipmentService_CreateShipment_FullMethodName       = "/shipment.ShipmentService/CreateShipment"
	ShipmentService_TrackShipment_FullMethodName        = "/shipment.ShipmentService/TrackShipment"
	ShipmentService_GetShipmentByOrder_FullMethodName   = "/shipment.ShipmentService/GetShipmentByOrder"
	ShipmentService_GetAccountShipments_FullMethodName  = "/shipment.ShipmentService/GetAccountShipments"
)

// ShipmentServiceClient is the client API for ShipmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShipmentServiceClient interface {
	CalculateRates(ctx context.Context, in *RateRequest, opts ...grpc.CallOption) (*MultiRateResponse, error)
	GetAvailableCouriers(ctx context.Context, in *AvailabilityRequest, opts ...grpc.CallOption) (*CourierListResponse, error)
	CreateShipment(ctx context.Context, in *CreateShipmentRequest, opts ...grpc.CallOption) (*ShipmentResponse, error)
	TrackShipment(ctx context.Context, in *TrackingRequest, opts ...grpc.CallOption) (*TrackingResponse, error)
	GetShipmentByOrder(ctx context.Context, in *OrderTrackingRequest, opts ...grpc.CallOption) (*ShipmentResponse, error)
	GetAccountShipments(ctx context.Context, in *AccountShipmentsRequest, opts ...grpc.CallOption) (*AccountShipmentsResponse, error)
}

type shipmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShipmentServiceClient(cc grpc.ClientConnInterface) ShipmentServiceClient {
	return &shipmentServiceClient{cc}
}

func (c *shipmentServiceClient) CalculateRates(ctx context.Context, in *RateRequest, opts ...grpc.CallOption) (*MultiRateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MultiRateResponse)
	err := c.cc.Invoke(ctx, ShipmentService_CalculateRates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shipmentServiceClient) GetAvailableCouriers(ctx context.Context, in *AvailabilityRequest, opts ...grpc.CallOption) (*CourierListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CourierListResponse)
	err := c.cc.Invoke(ctx, ShipmentService_GetAvailableCouriers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shipmentServiceClient) CreateShipment(ctx context.Context, in *CreateShipmentRequest, opts ...grpc.CallOption) (*ShipmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShipmentResponse)
	err := c.cc.Invoke(ctx, ShipmentService_CreateShipment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shipmentServiceClient) TrackShipment(ctx context.Context, in *TrackingRequest, opts ...grpc.CallOption) (*TrackingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrackingResponse)
	err := c.cc.Invoke(ctx, ShipmentService_TrackShipment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shipmentServiceClient) GetShipmentByOrder(ctx context.Context, in *OrderTrackingRequest, opts ...grpc.CallOption) (*ShipmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShipmentResponse)
	err := c.cc.Invoke(ctx, ShipmentService_GetShipmentByOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shipmentServiceClient) GetAccountShipments(ctx context.Context, in *AccountShipmentsRequest, opts ...grpc.CallOption) (*AccountShipmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountShipmentsResponse)
	err := c.cc.Invoke(ctx, ShipmentService_GetAccountShipments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShipmentServiceServer is the server API for ShipmentService service.
// All implementations must embed UnimplementedShipmentServiceServer
// for forward compatibility.
type ShipmentServiceServer interface {
	CalculateRates(context.Context, *RateRequest) (*MultiRateResponse, error)
	GetAvailableCouriers(context.Context, *AvailabilityRequest) (*CourierListResponse, error)
	CreateShipment(context.Context, *CreateShipmentRequest) (*ShipmentResponse, error)
	TrackShipment(context.Context, *TrackingRequest) (*TrackingResponse, error)
	GetShipmentByOrder(context.Context, *OrderTrackingRequest) (*ShipmentResponse, error)
	GetAccountShipments(context.Context, *AccountShipmentsRequest) (*AccountShipmentsResponse, error)
	mustEmbedUnimplementedShipmentServiceServer()
}

// UnimplementedShipmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShipmentServiceServer struct{}

func (UnimplementedShipmentServiceServer) CalculateRates(context.Context, *RateRequest) (*MultiRateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateRates not implemented")
}
func (UnimplementedShipmentServiceServer) GetAvailableCouriers(context.Context, *AvailabilityRequest) (*CourierListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvailableCouriers not implemented")
}
func (UnimplementedShipmentServiceServer) CreateShipment(context.Context, *CreateShipmentRequest) (*ShipmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateShipment not implemented")
}
func (UnimplementedShipmentServiceServer) TrackShipment(context.Context, *TrackingRequest) (*TrackingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrackShipment not implemented")
}
func (UnimplementedShipmentServiceServer) GetShipmentByOrder(context.Context, *OrderTrackingRequest) (*ShipmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShipmentByOrder not implemented")
}
func (UnimplementedShipmentServiceServer) GetAccountShipments(context.Context, *AccountShipmentsRequest) (*AccountShipmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountShipments not implemented")
}
func (UnimplementedShipmentServiceServer) mustEmbedUnimplementedShipmentServiceServer() {}
func (UnimplementedShipmentServiceServer) testEmbeddedByValue()                         {}

// UnsafeShipmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShipmentServiceServer will
// result in compilation errors.
type UnsafeShipmentServiceServer interface {
	mustEmbedUnimplementedShipmentServiceServer()
}

func RegisterShipmentServiceServer(s grpc.ServiceRegistrar, srv ShipmentServiceServer) {
	// If the following call pancis, it indicates UnimplementedShipmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShipmentService_ServiceDesc, srv)
}

func _ShipmentService_CalculateRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShipmentServiceServer).CalculateRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShipmentService_CalculateRates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShipmentServiceServer).CalculateRates(ctx, req.(*RateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShipmentService_GetAvailableCouriers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShipmentServiceServer).GetAvailableCouriers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShipmentService_GetAvailableCouriers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShipmentServiceServer).GetAvailableCouriers(ctx, req.(*AvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShipmentService_CreateShipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShipmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShipmentServiceServer).CreateShipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShipmentService_CreateShipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShipmentServiceServer).CreateShipment(ctx, req.(*CreateShipmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShipmentService_TrackShipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShipmentServiceServer).TrackShipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShipmentService_TrackShipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShipmentServiceServer).TrackShipment(ctx, req.(*TrackingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShipmentService_GetShipmentByOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderTrackingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShipmentServiceServer).GetShipmentByOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShipmentService_GetShipmentByOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShipmentServiceServer).GetShipmentByOrder(ctx, req.(*OrderTrackingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShipmentService_GetAccountShipments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountShipmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShipmentServiceServer).GetAccountShipments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShipmentService_GetAccountShipments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShipmentServiceServer).GetAccountShipments(ctx, req.(*AccountShipmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShipmentService_ServiceDesc is the grpc.ServiceDesc for ShipmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShipmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shipment.ShipmentService",
	HandlerType: (*ShipmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateRates",
			Handler:    _ShipmentService_CalculateRates_Handler,
		},
		{
			MethodName: "GetAvailableCouriers",
			Handler:    _ShipmentService_GetAvailableCouriers_Handler,
		},
		{
			MethodName: "CreateShipment",
			Handler:    _ShipmentService_CreateShipment_Handler,
		},
		{
			MethodName: "TrackShipment",
			Handler:    _ShipmentService_TrackShipment_Handler,
		},
		{
			MethodName: "GetShipmentByOrder",
			Handler:    _ShipmentService_GetShipmentByOrder_Handler,
		},
		{
			MethodName: "GetAccountShipments",
			Handler:    _ShipmentService_GetAccountShipments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/shipment.proto",
}
